---
title: "HW2-lgraff"
author: "Lindsay Graff"
date: "October 4, 2019"
output: html_document
---

```{r setup, include=FALSE}
require(rgdal)
require(leaflet)
require(leaflet.extras)

require(dplyr)
require(readxl)
require(stringr)

require(raptr)
require(PBSmapping)
```

## Load shapefile

```{r }
FL_counties <- readOGR("FL_eviction_counties.geojson")
plot(FL_counties)

# Select a subset of columns
# poverty rate, median gross rent, median property value, num of evictions, eviction rate
FL_16 <- FL_counties
FL_16@data <- FL_16@data %>% 
  select(GEOID, west, south, north, n, pl, pr.16, mgr.16, mpv.16, e.16, er.16)
```

## Basemap

```{r basemap}
leaflet() %>%
  addProviderTiles(providers$OpenStreetMap)  

  #addPolygons(data = FL_16, weight = 1)
```

# Map with markers
```{r points}

# Calculate centroids of counties to find lat and long
FL_polyset <- SpatialPolygons2PolySet(x = FL_16)
centroid <- calcCentroid(FL_polyset, rollup = 1)

# Bind county centroids to Florida data
df_FL <- cbind(FL_16@data, centroid)

# Map with circle markers, radius defined by poverty rate
# Include a popup that lists the county's poverty rate
leaflet() %>%
  addProviderTiles(providers$OpenStreetMap) %>% 
  addPolygons(data = FL_16, weight = 1) %>% 
  addCircleMarkers(data = df_FL, lat = ~Y, lng = ~X, 
                   radius = ~log(pr.16),
                   popup = ~as.character(pr.16),
                   color = "red") 

```

```{r lines}

# Map with layer of lines
leaflet() %>% 
  addProviderTiles(providers$OpenStreetMap) %>% 
  addPolylines(data = FL_16, weight = 1) 
  
```

# Add polygons colored by median gross rent
```{r polygons}
# Make color palette for median gross rent (mgr)
bins <- c(500, 600, 700, 800, 900, 1000, 1100, 1200, 1300, 1400)
pal <- colorBin("YlOrRd", domain = df_FL$mgr.16, bins = bins)

# Map with layer of polygons, colored by mgr
leaflet() %>% 
  addProviderTiles(providers$OpenStreetMap) %>% 
  addPolygons(data = FL_16, weight = 1,
              fillColor = ~pal(mgr.16),
              fillOpacity = 0.8) %>% 
  addLegend(pal = pal, values = FL_16@data$mgr.16,
            labFormat = labelFormat(prefix = "$"))

```

# Add layersControl with two basemaps and two different layers
# Include quantile color palette by number of median property value
```{r layersControl}

# Create a continuous palette function
qpal <- colorQuantile("Blues", df_FL$mpv.16, n = 5)

# Create two basemaps with layers control. Color the map by quantile of median property value
leaflet() %>%
  addProviderTiles(providers$OpenStreetMap, group = "Open Street") %>% 
  addProviderTiles(providers$Esri.WorldStreetMap, group = "Esri World Street") %>% 
  addLayersControl(
    baseGroups = c("Open Street", "Esri World Street"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>% 
  addPolygons(data = FL_16, weight = 1,
              smoothFactor = .2,
              fillOpacity = .8,
              fillColor = ~qpal(df_FL$mpv.16)) %>% 
  addLegend(pal = qpal, values = df_FL$mpv.16)
  
```
